// Verified names and mode differences are documented in docs/RESEARCH.md.
// Combat values beyond the four requested base profiles are remake balance values.
export const WEAPONS = [
  {
    id: "club",
    name: "Spiked Club",
    family: "melee",
    damage: 5,
    rate: 0.32,
    range: 92,
    price: 0,
    ammo: null,
    color: "#af7951",
  },
  {
    id: "usp",
    name: "USP .45",
    family: "pistol",
    damage: 10,
    rate: 0.36,
    price: 0,
    ammo: null,
    color: "#929eab",
  },
  {
    id: "spas",
    name: "SPAS-12",
    family: "shotgun",
    damage: 25,
    rate: 0.7,
    price: 0,
    ammo: "shells",
    color: "#ae8b55",
  },
  {
    id: "tec",
    name: "TEC-DC9",
    family: "smg",
    damage: 6,
    rate: 0.085,
    price: 0,
    ammo: "smg",
    color: "#8694a4",
  },
  {
    id: "magnum",
    name: ".44 Magnum",
    family: "pistol",
    damage: 22,
    rate: 0.5,
    price: 1200,
    ammo: null,
    color: "#c8ced2",
  },
  {
    id: "m9",
    name: "M9",
    family: "pistol",
    damage: 14,
    rate: 0.25,
    price: 900,
    ammo: null,
    color: "#87969b",
  },
  {
    id: "eagle",
    name: "Desert Eagle",
    family: "pistol",
    damage: 35,
    rate: 0.55,
    price: 3000,
    ammo: null,
    color: "#d1cbb3",
  },
  {
    id: "aa12",
    name: "AA-12",
    family: "shotgun",
    damage: 32,
    rate: 0.35,
    price: 4500,
    ammo: "shells",
    color: "#819496",
  },
  {
    id: "m1014",
    name: "M1014",
    family: "shotgun",
    damage: 40,
    rate: 0.65,
    price: 5000,
    ammo: "shells",
    color: "#a6b0b1",
  },
  {
    id: "1887",
    name: "Model 1887",
    family: "shotgun",
    damage: 46,
    rate: 0.85,
    price: 6000,
    ammo: "shells",
    color: "#bc9666",
  },
  {
    id: "scar",
    name: "SCAR-H",
    family: "rifle",
    damage: 18,
    rate: 0.18,
    price: 4000,
    ammo: "rifle",
    color: "#c0ae79",
  },
  {
    id: "m16",
    name: "M16A4",
    family: "rifle",
    damage: 14,
    rate: 0.12,
    price: 4500,
    ammo: "rifle",
    color: "#84999b",
  },
  {
    id: "ak47",
    name: "AK47",
    family: "rifle",
    damage: 21,
    rate: 0.17,
    price: 5500,
    ammo: "rifle",
    color: "#ab7754",
  },
  {
    id: "m61",
    name: "M61",
    family: "rifle",
    damage: 9,
    rate: 0.055,
    price: 9000,
    ammo: "rifle",
    color: "#a0aeb0",
  },
  {
    id: "mp5",
    name: "MP5K",
    family: "smg",
    damage: 10,
    rate: 0.095,
    price: 2500,
    ammo: "smg",
    color: "#9ba6b2",
  },
  {
    id: "ump",
    name: "UMP45",
    family: "smg",
    damage: 14,
    rate: 0.13,
    price: 3500,
    ammo: "smg",
    color: "#809592",
  },
  {
    id: "kriss",
    name: "KRISS",
    family: "smg",
    damage: 11,
    rate: 0.07,
    price: 6000,
    ammo: "smg",
    color: "#bcc3c0",
  },
  {
    id: "grenade",
    name: "Grenade Launcher",
    family: "launcher",
    damage: 65,
    rate: 0.8,
    price: 7500,
    ammo: "rockets",
    color: "#b6b496",
  },
  {
    id: "rocket",
    name: "Rocket Launcher",
    family: "launcher",
    damage: 95,
    rate: 1.15,
    price: 10000,
    ammo: "rockets",
    color: "#8d9e6d",
  },
  {
    id: "crowbar",
    name: "Crowbar",
    family: "melee",
    damage: 10,
    rate: 0.25,
    range: 100,
    price: 700,
    ammo: null,
    color: "#ce6560",
  },
  {
    id: "axe",
    name: "Fireman’s Axe",
    family: "melee",
    damage: 25,
    rate: 0.55,
    range: 105,
    price: 2200,
    ammo: null,
    color: "#b1bfc0",
  },
  {
    id: "chainsaw",
    name: "Chainsaw",
    family: "melee",
    damage: 8,
    rate: 0.08,
    range: 95,
    price: 5500,
    ammo: null,
    color: "#daba54",
  },
  {
    id: "saw",
    name: "Buzz-saw Launcher",
    family: "saw",
    damage: 32,
    rate: 0.4,
    price: 8500,
    ammo: "energy",
    color: "#b0bdc6",
  },
  {
    id: "flame",
    name: "Flamethrower",
    family: "flame",
    damage: 9,
    rate: 0.09,
    price: 9000,
    ammo: "energy",
    color: "#e4a245",
  },
  {
    id: "laser",
    name: "Laser Gun",
    family: "laser",
    damage: 30,
    rate: 0.23,
    price: 12000,
    ammo: "energy",
    color: "#81d1cf",
  },
  {
    id: "sword",
    name: "Light Sword",
    family: "melee",
    damage: 35,
    rate: 0.23,
    range: 120,
    price: 16000,
    ammo: null,
    color: "#8dde74",
    super: true,
  },
  {
    id: "force",
    name: "Force Throw",
    family: "force",
    damage: 42,
    rate: 0.7,
    price: 18000,
    ammo: "energy",
    color: "#8ebbea",
    super: true,
  },
  {
    id: "stars",
    name: "Ninja Stars",
    family: "saw",
    damage: 20,
    rate: 0.14,
    price: 14000,
    ammo: "energy",
    color: "#d7d6cd",
    super: true,
  },
  {
    id: "crate",
    name: "Warrior Crate",
    family: "melee",
    damage: 50,
    rate: 0.65,
    range: 115,
    price: 16000,
    ammo: null,
    color: "#af7651",
    super: true,
  },
];
export const HEROES = [
  {
    id: "kid",
    name: "Super Kid",
    description: "The original survivor.",
    color: "#df3934",
    price: 0,
    weapon: 1,
  },
  {
    id: "soldier",
    name: "Soldier",
    description: "A steady hand. A sharp eye.",
    color: "#9b936d",
    price: 15000,
    weapon: 3,
  },
  {
    id: "ninja",
    name: "Ninja",
    description: "Quick strikes. No mercy.",
    color: "#786277",
    price: 18000,
    weapon: 0,
  },
  {
    id: "knight",
    name: "Force Knight",
    description: "Master of the light sword.",
    color: "#a09173",
    price: 25000,
    weapon: 25,
  },
  {
    id: "girl",
    name: "Warrior Girl",
    description: "Small hero. Heavy hitter.",
    color: "#e9e6cd",
    price: 20000,
    weapon: 28,
  },
];
export const BIOMES = [
  {
    id: "jungle",
    name: "Lost Jungle",
    label: "Vines, teeth & trouble",
    sky: ["#173b40", "#92bea9"],
    ground: "#83b365",
  },
  {
    id: "city",
    name: "Ruined City",
    label: "The original City Sweep",
    sky: ["#394353", "#798898"],
    ground: "#8b9696",
  },
  {
    id: "blossom",
    name: "Cherry Village",
    label: "A fight under the blossoms",
    sky: ["#97d88f", "#d1e8a4"],
    ground: "#a8ab7e",
  },
  {
    id: "waste",
    name: "Wasteland",
    label: "Thunder on the horizon",
    sky: ["#141d2d", "#947271"],
    ground: "#9a7957",
  },
  {
    id: "cave",
    name: "Dino Cavern",
    label: "Something big lives here",
    sky: ["#35261f", "#79502b"],
    ground: "#8c623a",
  },
  {
    id: "snow",
    name: "Frozen Frontier",
    label: "Cold hands. Hot barrels.",
    sky: ["#506e85", "#c5dee1"],
    ground: "#c7dcd8",
  },
];
export const MODES = {
  classic: [
    {
      id: "city",
      name: "CITY SWEEP",
      detail: "Clear the streets. Stock up at Ammo Country.",
      biome: "city",
      objective: "kills",
      target: 15,
    },
    {
      id: "blitz",
      name: "JUNGLE BLITZ",
      detail: "Keep shooting. Survive as long as you can.",
      biome: "jungle",
      objective: "endless",
      target: 0,
    },
  ],
  sequel: [
    {
      id: "missions",
      name: "MISSIONS",
      detail: "Kill, survive, travel & steal dinosaur eggs.",
      biome: "jungle",
      objective: "kills",
      target: 25,
    },
    {
      id: "arena",
      name: "ARENA",
      detail: "Endless waves. One last survivor.",
      biome: "jungle",
      objective: "endless",
      target: 0,
    },
  ],
};
export const AMMO = [
  { key: "shells", name: "SHOTGUN SHELLS", amount: 20, cost: 300 },
  { key: "smg", name: "SMG ROUNDS", amount: 120, cost: 400 },
  { key: "rifle", name: "RIFLE ROUNDS", amount: 100, cost: 500 },
  { key: "rockets", name: "EXPLOSIVE ROUNDS", amount: 10, cost: 800 },
  { key: "energy", name: "ENERGY CELLS", amount: 80, cost: 600 },
];
export const BASE_PROFILE = {
  version: 2,
  cash: 0,
  level: 1,
  exp: 0,
  ammo: { shells: 30, smg: 180, rifle: 100, rockets: 10, energy: 80 },
  upgrades: Array(WEAPONS.length).fill(0),
  unlocked: [0, 1, 2, 3],
  heroes: ["kid"],
  heroUpgrades: {},
  allies: [],
  best: 0,
  day: 1,
  edition: "sequel",
  hero: "kid",
};
export function normalizeProfile(raw = {}) {
  const p = { ...structuredClone(BASE_PROFILE), ...raw, version: 2 };
  p.ammo = { ...BASE_PROFILE.ammo, ...raw.ammo };
  if (!raw.ammo) {
    p.ammo.shells = raw.shells ?? 30;
    p.ammo.smg = raw.smg ?? 180;
  }
  p.upgrades = WEAPONS.map((_, i) => Number(raw.upgrades?.[i]) || 0);
  p.unlocked = [...new Set([0, 1, 2, 3, ...(raw.unlocked || [])])].filter(
    (i) => WEAPONS[i],
  );
  p.heroes = [...new Set(["kid", ...(raw.heroes || [])])];
  p.allies = (raw.allies || [])
    .map((id) =>
      id === "Soldier" ? "soldier" : id === "Force Knight" ? "knight" : id,
    )
    .filter((id) => ["soldier", "knight"].includes(id));
  p.heroUpgrades = raw.heroUpgrades || {};
  p.hero = HEROES.some((h) => h.id === p.hero) ? p.hero : "kid";
  p.edition = p.edition === "classic" ? "classic" : "sequel";
  return p;
}
export function loadProfile() {
  try {
    return normalizeProfile(
      JSON.parse(localStorage.getItem("dino-cap-save") || "{}"),
    );
  } catch {
    return normalizeProfile();
  }
}
