import React,{useState,useEffect,useRef} from 'react';
import{createRoot}from'react-dom/client';
import{Crosshair,Volume2,VolumeX,Maximize,Pause,Play,ArrowUpRight,Shield,Coins,ChevronRight,Swords,Target,Zap,Package,Heart,ArrowLeft,Settings,X,Check,Skull,Leaf}from'lucide-react';
import{Game,WEAPONS,initialProfile}from'./game';
import './style.css';
const icons=[Swords,Target,Crosshair,Zap];
function load(){try{return {...initialProfile,...JSON.parse(localStorage.getItem('dino-cap-save')||'{}')}}catch{return structuredClone(initialProfile)}}
function App(){const[profile,setProfile]=useState(load),[screen,setScreen]=useState('menu'),[tab,setTab]=useState('Play'),[hud,setHud]=useState({hp:100,weapon:1,kills:0,wave:1,waveKills:0,target:10,time:0}),[muted,setMuted]=useState(false),[help,setHelp]=useState(false),[notice,setNotice]=useState(''),[shopTab,setShopTab]=useState('Weapons');const canvas=useRef(),game=useRef(),stage=useRef();const screenRef=useRef(screen);screenRef.current=screen;
 useEffect(()=>{localStorage.setItem('dino-cap-save',JSON.stringify(profile))},[profile]);
 useEffect(()=>{const g=new Game(canvas.current,load(),data=>{setHud(data);setProfile(data.profile)},p=>{setProfile(p);setScreen('dead')});game.current=g;const down=e=>{const g=game.current;if(['ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();g.keys[e.key.toLowerCase()]=true;g.keys[e.key]=true;if(e.repeat)return;if(screenRef.current==='playing'&&['q','e','1','2','3','4'].includes(e.key.toLowerCase())){g.weapon=/[1-4]/.test(e.key)?Number(e.key)-1:(g.weapon+(e.key.toLowerCase()==='q'?3:1))%4;g.emit()}if(e.key==='Escape'&&['playing','paused'].includes(screenRef.current)){g.paused=!g.paused;g.mouse.down=false;setScreen(g.paused?'paused':'playing')}};const up=e=>{const g=game.current;g.keys[e.key]=false;g.keys[e.key.toLowerCase()]=false};const release=()=>game.current.mouse.down=false;const blur=()=>{const g=game.current;g.keys={};g.mouse.down=false;if(screenRef.current==='playing'){g.paused=true;setScreen('paused')}};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('pointerup',release);window.addEventListener('blur',blur);return()=>{game.current.destroy();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('pointerup',release);window.removeEventListener('blur',blur)}},[]);
 const start=()=>{game.current.destroy();game.current=new Game(canvas.current,profile,d=>{setHud(d);setProfile(d.profile)},p=>{setProfile(p);setScreen('dead')});game.current.muted=muted;game.current.start();setScreen('playing');setTab('Play')};
 const pause=()=>{game.current.paused=true;game.current.mouse.down=false;setScreen('paused')};const resume=()=>{game.current.profile=structuredClone(profile);game.current.paused=false;setScreen('playing')};
 const openShop=()=>{if(screen==='playing')game.current.paused=true;game.current.mouse.down=false;setScreen(screen==='playing'||screen==='paused'?'shop-paused':'shop');setTab('Armory')};
 const buy=(price,apply)=>{if(profile.cash<price){setNotice('Not enough cash. Head into the jungle to earn more.');return}setProfile(p=>{const n=structuredClone(p);n.cash-=price;apply(n);return n});setNotice('Added to your loadout. Ready for the jungle.');setTimeout(()=>setNotice(''),3500)};
 const isShop=screen.startsWith('shop'),isRun=['playing','paused','shop-paused','dead'].includes(screen);const format=n=>n.toLocaleString();
 return <div className="app"><header><a className="brand" href="#" onClick={e=>{e.preventDefault();if(screen==='playing')pause();else{setScreen('menu');setTab('Play')}}}><div className="brand-icon"><Skull size={25}/></div><span>DINO<span className="orange">CAP</span><small>SURVIVAL CLUB</small></span></a><nav>{['Play','Armory','Field Guide'].map(t=><button className={tab===t?'active':''} onClick={()=>{if(t==='Armory')openShop();else if(t==='Field Guide'){setTab(t);setHelp(true)}else{setTab(t);if(isShop)setScreen(screen==='shop-paused'?'paused':'menu')}}} key={t}>{t}</button>)}</nav><div className="account"><div className="cash"><Coins size={17}/>{format(profile.cash)}<span>CASH</span></div><div className="rank">{profile.level}</div><div className="rank-text">Rookie<small>LEVEL {profile.level}</small></div></div></header>
 <main><div className="page-heading"><div><div className="eyebrow"><span/> THE LAST HUMAN. THE FIRST WAVE.</div><h1>Welcome to the wild.</h1><p>They had their time. Now it’s your turn to survive.</p></div><div className="status"><span/> ALL SYSTEMS GO <small>LOCAL SAVE ACTIVE</small></div></div>
 <section className="arena" ref={stage}><div className="arena-top"><div><Leaf size={16}/><b>THE LOST JUNGLE</b><span>SECTOR 01</span></div><div className="arena-tools"><span className="live-dot"/> SURVIVAL MODE <i/><button title={muted?'Enable sound':'Mute sound'} onClick={()=>{setMuted(!muted);game.current.muted=!muted}}>{muted?<VolumeX size={17}/>:<Volume2 size={17}/>}</button><button title="Fullscreen" onClick={()=>document.fullscreenElement?document.exitFullscreen():stage.current.requestFullscreen()}><Maximize size={16}/></button></div></div>
 <div className={'canvas-wrap '+(screen==='playing'?'running':'')}><canvas ref={canvas} onPointerMove={e=>{const r=canvas.current.getBoundingClientRect();game.current.mouse.x=(e.clientX-r.left)/r.width*1080;game.current.mouse.y=(e.clientY-r.top)/r.height*500}} onPointerDown={e=>{if(screen==='playing'){e.preventDefault();game.current.mouse.down=true;canvas.current.setPointerCapture(e.pointerId)}}} onContextMenu={e=>e.preventDefault()}/>
 {isRun&&!isShop&&<div className="hud"><div className="player-hud"><div className="hp-label"><Heart size={13}/> HP <b>{Math.ceil(hud.hp)} / 100</b></div><div className="bar"><div style={{width: hud.hp+'%',background:hud.hp<30?'#dc6650':''}}/></div><div className="exp-line">LVL {profile.level}<div className="exp-bar"><i style={{width:profile.exp/(profile.level*100)*100+'%'}}/></div>{Math.round(profile.exp/(profile.level*100)*100)}%</div><p>{WEAPONS[hud.weapon].name} <span>{WEAPONS[hud.weapon].ammo?profile[WEAPONS[hud.weapon].ammo]:'∞'} AMMO</span></p></div><div className="wave-hud"><b>WAVE {String(hud.wave).padStart(2,'0')}</b><p>{hud.waveKills} / {hud.target} KILLS</p><span><Coins size={14}/> {format(profile.cash)}</span><button title="Pause" onClick={pause}><Pause size={18}/></button></div></div>}
 {screen==='menu'&&<><div className="scene-badge"><span/> ENDLESS SURVIVAL <i>•</i> JUNGLE</div><div className="hero-content"><div className="overline">LOCK. LOAD. LAST.</div><div className="game-title">DINO<span>CAP</span><div>SURVIVAL</div></div><p>A whole jungle wants you dead.<br/>Make them work for it.</p><button className="primary start" onClick={start}><Play size={18} fill="currentColor"/> ENTER THE JUNGLE <ChevronRight size={19}/></button><div className="hero-meta"><Shield size={13}/> LEVEL {profile.level} <i/> BEST RUN: {profile.best} KILLS</div></div><div className="scene-note"><span>01</span><div>NO WAY BACK.<small>JUST ONE MORE WAVE.</small></div></div></>}
 {screen==='paused'&&<div className="overlay"><div className="dialog"><div className="eyebrow">TAKE A BREATHER</div><h2>Game paused.</h2><p>The jungle can wait a minute.</p><button className="primary" onClick={resume}><Play size={17}/> BACK TO THE FIGHT</button><button className="secondary" onClick={openShop}>VISIT ARMORY</button><button className="text-btn" onClick={()=>{setScreen('menu');game.current.time=0}}>Return to main menu</button></div></div>}
 {screen==='dead'&&<div className="overlay"><div className="dialog"><Skull size={38} className="orange"/><h2>YOU DIED</h2><p>The jungle always gets its way. Until next time.</p><div className="run-stats"><div><b>{hud.kills}</b><small>KILLS</small></div><div><b>{format(hud.earned)}</b><small>CASH EARNED</small></div><div><b>{hud.wave}</b><small>WAVE REACHED</small></div></div><button className="primary" onClick={start}><Play size={16}/> ONE MORE RUN</button><button className="secondary" onClick={openShop}>MAIN MENU / ARMORY</button></div></div>}
 {isShop&&<div className="shop"><div className="shop-head"><div><div className="eyebrow">BETTER GEAR. BETTER ODDS.</div><h2>The Armory</h2></div><button className="secondary" onClick={()=>{setTab('Play');setScreen(screen==='shop-paused'?'paused':'menu');game.current.profile=structuredClone(profile)}}><ArrowLeft size={15}/> BACK</button></div><div className="shop-tabs">{['Weapons','Ammo','Mercenaries'].map(t=><button className={shopTab===t?'selected':''} onClick={()=>{setShopTab(t);setNotice('')}} key={t}>{t}</button>)}</div><div className="shop-grid">{shopTab==='Weapons'?WEAPONS.map((w,i)=>{const Icon=icons[i];const price=250*(profile.upgrades[i]+1);return <div className="shop-card" key={w.name}><Icon size={36}/><h3>{w.name}</h3><p>{w.damage+2*profile.upgrades[i]} DAMAGE <span>LVL {profile.upgrades[i]}</span></p><small>+2 attack power per upgrade</small><button className="secondary" onClick={()=>buy(price,p=>p.upgrades[i]++)}>UPGRADE · {format(price)} <Coins size={13}/></button></div>}):shopTab==='Ammo'?[['Shotgun shells','shells',20,300],['SMG rounds','smg',120,400]].map(([name,key,amount,price])=><div className="shop-card" key={key}><Package size={36}/><h3>{name}</h3><p>{profile[key]} IN INVENTORY</p><small>Refill +{amount} rounds</small><button className="secondary" onClick={()=>buy(price,p=>p[key]+=amount)}>BUY · {price} <Coins size={13}/></button></div>):[['Soldier',15000,'A steady aim. A loyal ally. Ranged support.'],['Force Knight',25000,'Close combat specialist. Heavy melee strikes.']].map(([name,price,desc])=><div className="shop-card" key={name}><Shield size={36}/><h3>{name}</h3><p>{desc}</p><small>Follows you and attacks automatically</small><button className="secondary" disabled={profile.allies.includes(name)} onClick={()=>buy(price,p=>p.allies.push(name))}>{profile.allies.includes(name)?'HIRED ✓':`HIRE · ${format(price)}`}</button></div>)}</div><div className="shop-notice">{notice||'All purchases and upgrades are saved automatically.'}</div></div>}
 </div><div className="arena-footer"><span><span className="green-dot"/> {screen==='playing'?'YOU’RE IN. STAY ALIVE.':'READY WHEN YOU ARE.'}</span><span><Shield size={13}/> PROGRESS SAVES AUTOMATICALLY</span><button onClick={()=>setHelp(true)}>HOW TO PLAY <ArrowUpRight size={14}/></button></div></section>
 <section className="loadout-section"><div className="section-heading"><h2><Swords size={17}/> Your loadout <span>4 WEAPONS. ONE SURVIVOR.</span></h2><button onClick={openShop}>Visit armory <ArrowUpRight size={16}/></button></div><div className="loadout-grid">{WEAPONS.map((w,i)=>{const Icon=icons[i];return <button key={w.name} className={'weapon-card '+(hud.weapon===i?'equipped':'')} onClick={()=>{game.current.profile=structuredClone(profile);game.current.weapon=i;game.current.emit()}}><div className="weapon-top"><span className="keycap">{i+1}</span><small>{hud.weapon===i?'EQUIPPED':i>1?'SPECIAL':'STANDARD'}</small><span className="weapon-indicator"/></div><div className="weapon-art"><WeaponArt index={i}/></div><div className="weapon-bottom"><div><h3>{w.name}</h3><p>{['CLOSE & PERSONAL','EVERY SHOT COUNTS','MAKE SOME SPACE','SPRAY & SURVIVE'][i]}</p></div><div className="ammo">{w.ammo?profile[w.ammo]:'∞'}<small>{w.ammo?'ROUNDS':'AMMO'}</small></div></div><div className="weapon-stats"><span><Crosshair size={11}/>{w.damage+profile.upgrades[i]*2} DMG</span><span>{['MELEE','SEMI-AUTO','SPREAD','FULL-AUTO'][i]}</span></div></button>})}</div></section>
 <section className="bottom-row"><div className="controls"><span className="small-label">SURVIVAL BASICS</span><div><kbd>A</kbd><kbd>D</kbd><span>Move</span><span className="mouse-icon">♧</span><span>Aim & shoot</span><kbd>Q</kbd><kbd>E</kbd><span>Switch weapon</span><kbd>ESC</kbd><span>Pause</span></div></div><div className="tip"><div className="tip-icon"><Zap size={20}/></div><div><span className="small-label">FIELD TIP #01</span><p>Keep moving. A standing target is an easy meal.</p></div></div></section>
 </main><footer><span>© 2026 DINO CAP <i/> BUILT FOR ONE MORE RUN.</span><span><span className="green-dot"/> OFFLINE READY <i/> v1.0</span></footer>
 {help&&<div className="modal-backdrop"><div className="guide"><button className="close" onClick={()=>{setHelp(false);setTab(isShop?'Armory':'Play')}}><X size={20}/></button><div className="eyebrow">KNOW YOUR ENEMY</div><h2>Field guide</h2><p>Move with A/D or arrow keys. Aim with your mouse and hold left-click to attack. Q/E or 1–4 switch weapons. Escape pauses the fight.</p><div className="enemy-guide"><div><b>Velociraptor</b><span>20 HP · 10 DMG</span><p>Fast. Small. Lunges when close. Keep your distance.</p></div><div><b>Large Brute</b><span>150 HP · 35 DMG</span><p>Slow, tough, and resistant to knockback. Focus your fire.</p></div><div><b>Blue Mutant</b><span>50 HP · ACID SPIT</span><p>Ranged acid attacks. Watch the green projectiles.</p></div></div><p>Collect health packs for +25 HP and crates for ammo. Kills earn cash and EXP. Each level restores 25 HP. Visit the armory anytime from pause to improve your odds.</p><button className="primary" onClick={()=>{setHelp(false);setTab(isShop?'Armory':'Play')}}><Check size={16}/> GOT IT. LET’S SURVIVE.</button></div></div>}
 </div>}
function WeaponArt({index}){return <svg viewBox="0 0 240 65" aria-hidden="true"><defs><linearGradient id={'metal'+index} x2="0" y2="1"><stop stopColor="#a6ada0"/><stop offset="1" stopColor="#4c5850"/></linearGradient></defs><g transform="translate(38,8) rotate(-8 85 30)" stroke="#111b15" strokeWidth="3" strokeLinejoin="round">{index===0?<><path d="M54 33 L156 12 Q174 15 152 29 L58 46Z" fill="#b7c4b1"/><path d="M23 35 L58 32 L61 48 L26 52Z" fill="#a17849"/><path d="M30 37L32 48M40 35L42 47M50 35L51 45" stroke="#382b21"/></>:<><path d={index===2?'M30 19 H163 V31 H45 L33 43 H7 L5 35Z':index===3?'M36 14 H119 V36 H76 L68 56 H51 L57 35 H33Z':'M46 15 H125 V32 H81 L73 55 H53 L61 31 H46Z'} fill={'url(#metal'+index+')'}/><path d={index===2?'M48 26H109V38H48Z':index===3?'M79 36L90 55H103L96 35Z':'M61 33L55 52H72L78 33Z'} fill="#72745a"/><path d={index===2?'M105 22H173V28H105':index===3?'M119 20H146V30H119':'M124 20H136V27H124'} fill="#68766a"/><path d="M54 19H100" stroke="#c0c6b5" strokeWidth="2"/>{index===3&&<path d="M89 11V4H115V14" fill="none"/>}</>}</g></svg>}
createRoot(document.getElementById('root')).render(<App/>);
